##############################################################
### Passwordless root (not for apps that auth with policy-kit)
##############################################################
- name: Make sure user stepmania is in sudo group
  user:
    name: stepmania
    groups: sudo
    append: yes

- name: Enable passwordless sudo for stepmania
  lineinfile:
    destfile: /etc/sudoers
    line: 'stepmania ALL=(ALL) NOPASSWD:ALL'
    regexp: '^stepmania'
    validate: '/usr/sbin/visudo -cf %s'
    insertbefore: '^root '

####################################
### Disable automatic system updates
####################################
- name: Disable apt-daily-service.timer
  systemd:
    name: apt-daily-upgrade.timer
    enabled: no
    state: stopped

- name: Disable apt-daily.timer
  systemd:
    name: apt-daily.timer
    enabled: no
    state: stopped

#####################################
### Disable some autostart activities
#####################################
- name: Make sure .config/autostart folder exists
  file:
    dest: /home/stepmania/.config/autostart
    state: directory
    owner: stepmania
    group: stepmania

- name: Remove light-locker from autostart
  copy:
    src: files/disabled-autostart.desktop
    dest: /home/stepmania/.config/autostart/light-locker.desktop
    owner: stepmania
    group: stepmania

- name: Remove xscreensaver from autostart
  copy:
    src: files/disabled-autostart.desktop
    dest: /home/stepmania/.config/autostart/xscreensaver.desktop
    owner: stepmania
    group: stepmania

- name: Remove xfce4-power-manager from autostart
  copy:
    src: files/disabled-autostart.desktop
    dest: /home/stepmania/.config/autostart/xfce4-power-manager.desktop
    owner: stepmania
    group: stepmania

##################
### LIGHTDM CONFIG
##################
- name: Install LightDM configuration
  copy:
    src: files/custom.conf
    dest: /usr/share/lightdm/lightdm.conf.d/99_custom.conf

- name: Create nopasswdlogin group
  group:
    name: nopasswdlogin

- name: Add stepmania to nopasswdlogin group
  user:
    name: stepmania
    groups: nopasswdlogin
    append: yes

- name: Enable passwordless login in PAM
  lineinfile:
    destfile: /etc/pam.d/lightdm
#    path: /etc/pam.d/lightdm
    line: "auth  sufficient  pam_succeed_if.so user ingroup nopasswdlogin"
    insertafter: "#%PAM-1.0"

- name: Make sure user stepmania is in sudo group
  user:
    name: stepmania
    groups: sudo
    append: yes

- name: Enable passwordless sudo for stepmania
  lineinfile:
    destfile: '/etc/sudoers'
#    path: '/etc/sudoers'
    line: 'stepmania ALL=(ALL) NOPASSWD:ALL'
    regexp: '^stepmania'
    validate: '/usr/sbin/visudo -cf %s'
    insertbefore: '^root '
