- set_fact: PIUIO_VERSION=v1.0

- name: Install DKMS and other dependencies
  apt:
    package: "dkms,git,build-essential,linux-headers-{{ ansible_kernel }}"

- name: Get source
  git: 
    repo: https://github.com/djpohly/piuio
    dest: /usr/src/piuio-{{ PIUIO_VERSION }}
    version: "{{ PIUIO_VERSION }}"
  register: source

- name: Add DKMS configuration
  template:
    src: files/dkms.conf
    dest: /usr/src/piuio-{{ PIUIO_VERSION }}/dkms.conf
  register: config

- name: Remove old from DKMS
  shell: dkms remove -m piuio -v {{ PIUIO_VERSION }} --all || true
  when: config.changed or source.changed

- name: Add to DKMS
  shell: dkms add -m piuio -v {{ PIUIO_VERSION }}
  when: config.changed or source.changed

- name: Build and install module
  shell: dkms build -m piuio -v {{ PIUIO_VERSION }} && dkms install -m piuio -v {{PIUIO_VERSION}}
  when: config.changed or source.changed

- name: Enable kernel module
  modprobe:
    name: piuio

- name: Add to list of automatically load kernel modules
  copy:
    content: "piuio"
    dest: /etc/modules-load.d/piuio.conf
