#############################################
### INSTALL STEPMANIA, THEMES, NOTESKINS, ETC
#############################################
- name: Fetch Stepmania source
  git:
    repo: https://github.com/stepmania/stepmania
    dest: /opt/stepmania
    version: 5_1-new
    force: yes
  register: source

# - name: Removing
#   file:
#     dest: /opt/stepmania/extern/libmmmagic
#     state: absent
#
# - name: Fetch libmmmagic source
#   git:
#     repo: https://github.com/sl1pkn07/libmmmagic
#     dest: /opt/stepmania/extern/libmmmagic
#   register: source

- name: Run CMake Stepmania
  shell: cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release .. && cmake ..
  args:
    chdir: /opt/stepmania/Build
  when: source.changed

- name: Compile Stepmania
  shell: make -j$(nproc --all)
  args:
    chdir: /opt/stepmania/Build
  when: source.changed

##################
### INSTALL THEMES
##################
- name: Make sure theme directory exists
  file:
    dest: /home/stepmania/.stepmania-5.1/Themes
    # path: /home/stepmania/.stepmania-5.1/Themes
    state: directory
    owner: stepmania
    group: stepmania
    recurse: yes

- name: Fetch Simply Love for SM5
  git:
    repo: https://github.com/dguzek/Simply-Love-SM5
    dest: /home/stepmania/.stepmania-5.1/Themes/Simply-Love-SM5
  become_user: stepmania

# - name: Fetch Simply Love, McKylä edition
#   git:
#     repo: https://github.com/Kauhsa/Simply-Love-SM5
#     dest: /home/stepmania/.stepmania-5.1/Themes/Simply-Love-SM5
#     version: makkyla
#   become_user: stepmania

- name: Make sure vocalize directory exists
  file:
    dest: /home/stepmania/.stepmania-5.1/Themes/Simply-Love-SM5/Other/Vocalize/
   # path: /home/stepmania/.stepmania-5.1/Themes/Simply-Love-SM5/Other/Vocalize/
    state: directory
    owner: stepmania
    group: stepmania
    recurse: yes

- name: Install vocalize
  synchronize:
    src: files/Vocalize/
    dest: /home/stepmania/.stepmania-5.1/Themes/Simply-Love-SM5/Other/Vocalize/

#############
### NOTESKINS
#############
- name: Make sure noteskins directory exists
  file:
    dest: /home/stepmania/.stepmania-5.1/NoteSkins/dance
    # path: /home/stepmania/.stepmania-5.1/NoteSkins/dance
    state: directory
    owner: stepmania
    group: stepmania
    recurse: yes

- name: Install noteskins
  synchronize:
    src: files/noteskins/
    dest: /home/stepmania/.stepmania-5.1/NoteSkins/dance

######################
### STEPMANIA SETTINGS
######################
- name: Make sure Save directory exists
  file:
    dest: /home/stepmania/.stepmania-5.1/Save
    # path: /home/stepmania/.stepmania-5.1/Save
    state: directory
    owner: stepmania
    group: stepmania

# TO DO: variables for choosing among multiple devices.
- name: Install Default Keymaps.ini file
  copy:
    src: files/Keymaps-Default.ini
    dest: /home/stepmania/.stepmania-5.1/Save/Keymaps.ini
    owner: stepmania
    group: stepmania

#############################
### STARTUP AND DESKTOP ICONS
#############################
- name: Get localized Desktop path
  shell: xdg-user-dir DESKTOP
  register: desktop_output
  become_user: stepmania

- name: Copy startup script
  copy:
    src: files/start.sh
    dest: /home/stepmania/start-stepmania.sh
    mode: 0755
    owner: stepmania
    group: stepmania

- name: Make sure Desktop folder exists
  file:
    dest: "{{desktop_output.stdout}}"
    # path: {{desktop_output.stdout}}
    owner: stepmania
    group: stepmania
    state: directory

- name: Add Stepmania icon to desktop
  copy:
    src: files/stepmania.desktop
    dest: "{{desktop_output.stdout}}/stepmania.desktop"
    mode: 0755
    owner: stepmania
    group: stepmania

- name: Add link to Songs to Desktop
  file:
    src: /home/stepmania/.stepmania-5.1/Songs
    dest: "{{desktop_output.stdout}}/Songs"
    state: link
    force: yes

- name: Add link to Courses to Desktop
  file:
    src: /home/stepmania/.stepmania-5.1/Courses
    dest: "{{desktop_output.stdout}}/Courses"
    state: link
    force: yes

- name: Add link to Save to Desktop
  file:
    src: /home/stepmania/.stepmania-5.1/Save
    dest: "{{desktop_output.stdout}}/Save"
    state: link
    force: yes

- name: Make sure autostart directory exists
  file:
    dest: /home/stepmania/.config/autostart
    # path: /home/stepmania/.config/autostart
    state: directory
    owner: stepmania
    group: stepmania

- name: Run Stepmania on startup
  file:
    src: "{{desktop_output.stdout}}/stepmania.desktop"
    dest: /home/stepmania/.config/autostart/stepmania.desktop
    state: link
