- name: Add non-free repository
  apt_repository:
    repo: deb http://httpredir.debian.org/debian/ stretch main contrib non-free

- name: Blacklist nouveau
  kernel_blacklist:
    name: nouveau
    state: present

- name: Install nvidia-driver
  apt:
    package: nvidia-driver
    update_cache: yes

- name: Make sure X.org configuration directory exists
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: Install Xorg configuration file
  copy:
    src: files/20-nvidia.conf
    dest: /etc/X11/xorg.conf.d/20-nvidia.conf
