################
### ADD APT KEYS
################
- name: Install packages
  apt:
    package: apt-transport-https

- name: Add the WebUpd8 key
  apt_key: keyserver=keyserver.ubuntu.com id=7B2C3B0889BF5709A105D03AC2518248EEA14886 state=present

#- name: Add the GEANY key
#  apt_key: keyserver=keyserver.ubuntu.com id=3A68BA40877059E65867971771240B8FB3641232 state=present

#- name: Install packages
#  apt:
#    package: apt-transport-https

#- name: Add the SUBLIME 3 key
#  apt_key: url=https://download.sublimetext.com/sublimehq-pub.gpg id=F57D4F59BD3DF454 state=present


####################
### ADD REPOSITORIES
####################
#- name: Enable apt-pinning
#  copy:
#    src: files/use-unstable
#    dest: /etc/apt/preferences.d/use-unstable
#
#- name: Enable DEBIAN TESTING repository
#  apt_repository: repo="deb http://ftp.fi.debian.org/debian/ testing main" state=present update_cache=yes
#
#- name: Enable DEBIAN UNSTABLE repository
#  apt_repository: repo="deb http://ftp.fi.debian.org/debian/ unstable main" state=present update_cache=yes

- name: Add the WebUpd8 ATOM repository
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/atom/ubuntu artful main" state=present update_cache=yes

#- name: Add the GEANY repository
#  apt_repository: repo="deb http://ppa.launchpad.net/geany-dev/ppa/ubuntu artful main" state=present update_cache=yes

#- name: Add the WebUpd8 SUBLIME 3 repository
#  apt_repository: repo="deb https://download.sublimetext.com/ apt/stable/" state=present update_cache=yes

####################
### INSTALL PACKAGES
####################
- name: Install packages 1
  apt:
    package: atom,chromium,doublecmd-gtk,git,htop,jstest-gtk,lightdm,meld,nemo,net-tools,openssh-server,vim
    update_cache: yes

#- name: Install packages 2
#  apt:
#    package: geany,geany-plugins,sublime-text
#    update_cache: yes
