################
### ADD APT KEYS
################
#- name: Install packages
#  apt:
#    package: apt-transport-https

- name: Add the WebUpd8 key
  apt_key: keyserver=keyserver.ubuntu.com id=7B2C3B0889BF5709A105D03AC2518248EEA14886 state=present

####################
### ADD REPOSITORIES
####################
- name: Add the WebUpd8 ATOM repository
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial main" state=present update_cache=yes

- name: Enable Ubuntu repositories
  apt_repository: repo="deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse"

####################
### INSTALL PACKAGES
####################
- name: Install software packages
  apt:
    package: atom,chromium-browser,dconf-editor,doublecmd-gtk,htop,jstest-gtk,lightdm,net-tools,openssh-server,unclutter,vim,xterm
    update_cache: yes

- name: Install development dependencies
  apt:
    package: binutils-dev,build-essential,cmake,dkms,git,libasound-dev,libbz2-dev,libc6-dev,libglew1.5-dev,libglu1-mesa-dev,libgtk2.0-dev,libjpeg-dev,libmad0-dev,libogg-dev,libpng-dev,libpulse-dev,libudev-dev,libva-dev,libxrandr-dev,libxtst-dev,libvorbis-dev,linux-headers-{{ ansible_kernel }},meld,mesa-common-dev,yasm,zlib1g-dev
    update_cache: yes

- name: Uninstall unused software
  apt:
    package: vino
    update_cache: yes
